services:

  spring-auth:
    build:
      context: ..
      dockerfile: docker/spring-auth/Dockerfile
    ports:
      - "8081:8081"
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET:-my-very-secret-key-change-in-prod}

  resource-server:
    build:
      context: ..
      dockerfile: docker/resource-server/Dockerfile
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: ${JWT_SECRET:-my-very-secret-key-change-in-prod}

  web-client:
    build:
      context: ..
      dockerfile: docker/web-client/Dockerfile
    ports:
      - "4200:4200"
    depends_on:
      - spring-auth
      - resource-server
