services:

  spring-auth:
    build:
      context: ../spring-auth
    ports:
      - "8081:8081"
    environment:
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      JWT_SECRET: ${JWT_SECRET:-my-very-secret-key-change-in-prod}

  prompt-service:
    build:
      context: ../prompt-service
    ports:
      - "8082:8082"
    environment:
      JWT_SECRET: ${JWT_SECRET:-my-very-secret-key-change-in-prod}

  web-client:
    build:
      context: ../web-client
    ports:
      - "4200:4200"
    depends_on:
      - spring-auth
      - prompt-service
